### ISSUE TITLE
feature request/suggestion: Following tab

### ISSUE THREAD

**Issue by falafflepotatoe** [jameseunson/twitchy#1]
I would hope this would have a Following tab, maybe before Featured, to list the streams I always watch or [easier] have followed.

Cool stuff also

**Comment by jameseunson** [comment]
Hey,

Cool idea. I'll look at implementing this next week. Adding user authentication will also enable implementing chat, which is something I want to do.

**Comment by jameseunson** [comment]
This is now implemented. The app generates a code which is entered at http://twitchy.jeon.com.au/code. This then redirects to an OAuth registration endpoint in the Twitch.tv API. When the registration is complete, Twitch redirects back to http://twitchy.jeon.com.au with a unique OAuth token for the user. Meanwhile the TV app polls http://twitchy.jeon.com.au, waiting for the authentication to be complete, and offers to log the user in when complete. The login tab is then replaced by a Following tab. Logging in also enables chat while streaming, though this is definitely not complete, and sometimes crashes when chat moves too fast.

Thanks again for the suggestion
![simulator screen shot 11 may 2016 11 22 14 am](https://cloud.githubusercontent.com/assets/51029/15167417/2244d116-176c-11e6-805b-35e3fddd9096.png)
![simulator screen shot 11 may 2016 11 20 15 am](https://cloud.githubusercontent.com/assets/51029/15167418/224a846c-176c-11e6-8732-d38d3416f44e.png)
![simulator screen shot 11 may 2016 11 16 37 am](https://cloud.githubusercontent.com/assets/51029/15167419/224cd302-176c-11e6-975e-41ccc2315f14.png)
![simulator screen shot 11 may 2016 11 15 34 am](https://cloud.githubusercontent.com/assets/51029/15167420/224f6342-176c-11e6-829d-13db67282637.png)

**Comment by jameseunson** [comment]
Oh and the code for the backend server that does all the redirecting is available here: https://github.com/jameseunson/twitchy-backend
