### ISSUE TITLE
VOD not working

### ISSUE THREAD

**Issue by Chris230291** [jameseunson/twitchy#3]
I'm sure VOD's worked at some point but now they don't, highlights still work though.

When clicking on a VOD it tries to play but only shows a black screen. In the lower left there is a no-entry type symbol on the timeline.

Thanks,
Chris

**Comment by jameseunson** [comment]
Hey,

At some point a short while back Twitch changed their API to necessitate a valid 'client_id' parameter included with requests, which Twitchy doesn't support. I'll see if I can find a way to resolve this issue.

Cheers,
James

**Comment by Chris230291** [comment]
Thank you.

**Comment by jameseunson** [comment]
This is now resolved, apologies for the delay. Please pull the latest code from the repo.

**Comment by Chris230291** [comment]
That's great thanks.
